teste = {
  command: "SELECT",
  fields: [
    {
      columnID: 1,
      dataTypeID: 23,
      dataTypeModifier: -1,
      dataTypeSize: 4,
      format: "text",
      name: "id",
      tableID: 81921,
    },
    {
      columnID: 2,
      dataTypeID: 1043,
      dataTypeModifier: 259,
      dataTypeSize: -1,
      format: "text",
      name: "nome",
      tableID: 81921,
    },
    {
      columnID: 3,
      dataTypeID: 1043,
      dataTypeModifier: 19,
      dataTypeSize: -1,
      format: "text",
      name: "telefone",
      tableID: 81921,
    },
    {
      columnID: 4,
      dataTypeID: 1043,
      dataTypeModifier: 259,
      dataTypeSize: -1,
      format: "text",
      name: "email",
      tableID: 81921,
    },
    {
      columnID: 5,
      dataTypeID: 1043,
      dataTypeModifier: 259,
      dataTypeSize: -1,
      format: "text",
      name: "senha",
      tableID: 81921,
    },
    {
      columnID: 6,
      dataTypeID: 16,
      dataTypeModifier: -1,
      dataTypeSize: 1,
      format: "text",
      name: "isartist",
      tableID: 81921,
    },
  ],
  rowAsArray: false,
  rowCount: 1,
  rows: [
    {
      id: 2,
      nome: "robson",
      telefone: "2315632",
      email: "@email",
      senha: "$2b$10$90.zOTDcial7OgtsWoNM5eTQak9dSw2OMe3nABhTvmAWWtyeScPIa",
      isartist: true,
    },
  ],
  viaNeonFetch: true,
};
